(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g;function aa(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var l=aa(this),ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},p;
if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var r;a:{var ca={a:!0},t={};try{t.__proto__=ca;r=t.a;break a}catch(a){}r=!1}p=r?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var w=p;
function x(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(w)w(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ka=b.prototype}var da=this||self;function y(a,b,c,d){a="translate3d("+a+"px, "+b+"px, "+c+"px)";d&&(a="rotate3d(0, 1, 0, "+d+"deg) "+a);return a}function z(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a};var A=["-ms-","-moz-","-webkit-",""];function B(a,b,c,d){d=void 0===d?!1:d;for(var e,h,f=0;f<A.length;f++)e=A[f]+b,h=(d?A[f]:"")+c,a.style.setProperty(e,h)};function C(a,b){B(a,"transition","transform "+b+"ms",!0)};function D(a,b){return window.setTimeout(a,b)};function E(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d}function ea(a,b){b=void 0===b?null:b;var c=void 0===c?null:c;D(function(){var d=E("autoplayended",a,b);c&&c(d)},1)}function fa(a,b){function c(d){a.removeEventListener("attached",c);b(d)}a.addEventListener("attached",c)}function ha(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=D(function(){c=null;b&&(a(),b=!1)},250))}};function F(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function G(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")}function ia(a){if(G(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&G(a))return a;return null}
function H(a,b,c,d){d=(void 0===d?"":d)||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)}function ja(a){return(a=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):"")?a.split(",").map(function(b){return b.trim()}):[]};/*

 SPDX-License-Identifier: Apache-2.0
*/
function I(a,b){this.g=b===J?a:""}I.prototype.toString=function(){return this.g.toString()};I.prototype.l=!0;I.prototype.j=function(){return this.g.toString()};var ka=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,J={};function K(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;c++)if(!/^[\s\xa0]*$/.test(a[c])){var d=b,e=d.push;var h=a[c];h=h.trim();h=window.Enabler?window.Enabler.getUrl(h):h;var f=document.createElement("gwd-image");f.setAttribute("source",h);e.call(d,f)}}return b}function L(a,b){for(var c=0;c<a.length;c++){var d=a[c];"gwd-image"==d.tagName.toLowerCase()&&(null!=b?d.setAttribute("scaling",b):d.removeAttribute("scaling"))}}function M(a,b){return"left"==a||"backwards"==a?-b:b}
function N(a,b){return(a%b+b)%b};function la(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval}function O(a,b){this.g=a;this.j=null;this.m=b;this.l=!1}
function P(a,b,c){c=void 0===c?"forwards":c;if(a.g.frameCount&&null==a.j){var d=a.g.frameCount;b/=d;for(var e=[],h=la(a.g),f=h,k=0;k<d;k++){if(0<k||!a.m)f=N(f+M(c,1),a.g.frameCount);e.push(f)}c=function(){if(e.length){var n=e.shift();a.l=!0;a.g.goToFrame(n+1);a.l=!1;E("frameautoplayed",a.g,{id:n+1})}else a.stop(!0),a.g.goToFrame(h+1)};a.j=window.setInterval(c,b);setTimeout(c,1)}}
O.prototype.stop=function(a){a=void 0===a?!1:a;!this.l&&this.j&&(window.clearInterval(this.j),ea(this.g,{completed:a}),this.j=null)};var ma=["pause-front-media","resume-next-media"];function Q(){var a=HTMLElement.call(this)||this;a.frames=[];a.h=null;a.i=0;a.u=1;a.s=new O(a,!0);a.V=!1;a.W=!1;return a}x(Q,HTMLElement);g=Q.prototype;g.attributeChangedCallback=function(a,b,c){switch(a){case "pause-front-media":this.V="true"==c;break;case "resume-next-media":this.W="true"==c}};g.gwdIsLoaded=function(){return!0};g.gwdLoad=function(){};g.goToFrame=function(a,b){this.stopRotation();0!=this.i&&(a>this.i?a=this.i:1>a&&(a=1),this.T(a,b))};
g.T=function(a){this.h=a-1};function R(a,b,c,d){if(null!=a.h){var e=a.u;e=N(a.h+M(b,void 0===e?1:e),a.u*Math.ceil(a.i/a.u));!d&&("forwards"==b&&e<a.h||"backwards"==b&&e>a.h)||a.goToFrame(e+1,c)}}g.goBackwards=function(a,b){R(this,"backwards",void 0===a?"slide":a,void 0===b?!0:b)};g.goForwards=function(a,b){R(this,"forwards",void 0===a?"slide":a,void 0===b?!0:b)};g.rotateOnce=function(a,b){P(this.s,void 0===a?0:a,b)};g.stopRotation=function(){this.s.stop()};
g.getFrame=function(a){if(0!=this.i)return this.frames[a-1]};function S(a,b){if(null!=a.h&&a.h!=b){if(a.V)for(var c=Array.prototype.slice.call(a.frames[a.h].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),d=0;d<c.length;d++){var e=c[d];e.pause&&e.pause()}if(a.W)for(a=Array.prototype.slice.call(a.frames[b].querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")),b=0;b<a.length;b++)c=a[b],c.play&&c.play()}}
g.Y=function(a){var b=a.length;a=a.splice(0,b);for(var c=0;c<b;c++){var d=a[c];"frameshown"==d?E(d,this,{id:this.currentIndex}):E(d,this)}};l.Object.defineProperties(Q.prototype,{currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<this.i?this.h+1:void 0}},frameSnapInterval:{configurable:!0,enumerable:!0,get:function(){return this.u}},frameCount:{configurable:!0,enumerable:!0,get:function(){return this.i}}});
l.Object.defineProperties(Q,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ma}}});var na="autoplay exit-urls transition-duration frame-width frame-height neighbor-rotation-y neighbor-translation-x neighbor-translation-y neighbor-translation-z start-frame show-reflection has-navigation navigation-highlight navigation-thumbnails images scaling pause-front-media resume-next-media".split(" ");
function T(){var a=Q.call(this)||this;a.C=!1;a.l=null;a.K=-1;a.F=0;a.m=null;a.S=a.ga.bind(a);a.R=a.ha.bind(a);a.P=a.fa.bind(a);a.O=a.ea.bind(a);a.H=E.bind(null,"firstinteraction",a);a.M=a.da.bind(a);a.N=ha(a.X.bind(a));a.I=!1;a.D=[];a.o=a.Y.bind(a,a.D);a.G=[];a.J=0;a.A=!1;a.g=null;a.v=0;a.s=new O(a,!1);a.j=null;a.L=!1;a.B=!1;return a}x(T,Q);g=T.prototype;
g.connectedCallback=function(){if(!this.B){if(this.A=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);var a=document.createElement("gwd-gesture");a.className="gesture";this.m=a;this.B=!0}a=this.m;this.v=this.v||this.clientWidth/2;a.addEventListener("trackstart",this.S,!1);a.addEventListener("track",this.R,!1);a.addEventListener("trackend",this.P,!1);a.addEventListener("tap",this.O,!1);this.addEventListener("transitionend",this.o,!1);this.addEventListener("webkitTransitionEnd",
this.o,!1);this.gwdIsLoaded()||((a=ia(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());this.L&&U(this);window.addEventListener("resize",this.N,!1)};
g.disconnectedCallback=function(){window.removeEventListener("resize",this.N,!1);var a=this.m;a.removeEventListener("trackstart",this.S,!1);a.removeEventListener("track",this.R,!1);a.removeEventListener("trackend",this.P,!1);a.removeEventListener("tap",this.O,!1);this.removeEventListener("transitionend",this.o);this.removeEventListener("webkitTransitionEnd",this.o)};
g.attributeChangedCallback=function(a,b,c,d){switch(a){case "images":this.A=!0;this.i=0;this.h=null;this.frames=K(c||"");U(this);break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":this.B&&V(this);break;case "scaling":L(this.frames,c);break;case "pause-front-media":case "resume-next-media":Q.prototype.attributeChangedCallback.call(this,a,b,c,d);break;default:W(this)}};
g.T=function(a,b){b="none"!=b;var c=this.g.transitionDuration;S(this,a-1);X(this,b?c:0);Y(this,a-1)};g.rotateOnce=function(a,b){P(this.s,(void 0===a?0:a)||this.g.transitionDuration*this.i,b)};g.gwdIsLoaded=function(){return this.C};g.gwdLoad=function(){if(!this.C&&!this.l){if(this.A)var a=K(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;U(this)}};
function U(a){if(a.B){for(;a.firstChild;)a.removeChild(a.firstChild);a.j=null;a.l&&a.l.removeEventListener("pageload",a.M,!1);for(var b=a.frames,c=document.createElement("gwd-page"),d=0;d<b.length;d++){var e=b[d];B(e,"user-select","none");e.classList.add("frame");c.appendChild(e)}fa(c,c.gwdLoad.bind(c));a.l=c;c.className=a.hasAttribute("show-reflection")?"container reflection":"container";c.addEventListener("pageload",a.M,!1);L(a.frames,a.getAttribute("scaling"));a.appendChild(c);a.appendChild(a.m)}else a.L=
!0}g.da=function(a){this.l===a.target&&(this.C=!0,this.i=this.frames.length,this.G=[],this.J=this.i,Z(this),this.i&&this.g.autoplay&&D(this.rotateOnce.bind(this),0),V(this),E("allframesloaded",this),E("ready",this))};function Z(a){oa(a);if(a.i){var b=a.g.ia-1;if(0>b||b>=a.i)b=0;X(a,0);Y(a,b)}}g.X=function(){this.v=this.clientWidth/2;Z(this)};
function oa(a){W(a);for(var b=0,c,d=0;d<a.frames.length;d++)c=a.frames[d],c.style.left=b+"px",c.style.width=a.g.frameWidth+"px",c.style.height=a.g.frameHeight+"px",b+=a.g.frameWidth}
function W(a){var b=a.frames;var c=z(a,"frame-width",Math.floor(.8*a.clientWidth));var d=a.hasAttribute("show-reflection"),e=z(a,"frame-height",d?Math.floor(4*a.clientHeight/7):Math.floor(6*a.clientHeight/7)),h=z(a,"neighbor-translation-x",Math.floor(c/8));if(a.hasAttribute("neighbor-translation-x")){a:{var f=c,k=!0;a.hasAttribute("clamp-frame-size-to-image")&&(c=a.getAttribute("clamp-frame-size-to-image"),"true"==c?k=!0:"false"==c&&(k=!1));if(k)if(c=a.hasAttribute("scaling")?a.getAttribute("scaling"):
"contain",k="contain"==c,!k&&"none"!=c||0==f||0==e)b=f;else{c=-1;for(var n=b.length,u=0;u<n;u++){var m=b[u];if("img"!=m.tagName.toLowerCase()&&"gwd-image"!=m.tagName.toLowerCase()){b=f;break a}var q=m.assetWidth?m.assetWidth:m.naturalWidth;m=m.assetHeight?m.assetHeight:m.naturalHeight;if(0<q&&0<m){var v;k?v=q/m<f/e?q/m*e:f:v=q;c=Math.max(c,v)}}b=-1!=c?Math.min(f,c):f}else b=f}c=b}b=z(a,"neighbor-translation-y",-Math.floor(e/10));v=z(a,"neighbor-translation-z",-e);f=z(a,"neighbor-rotation-y",38);k=
z(a,"start-frame",2);u=e;a.j&&(u-=36);e=ja(a);n=a.hasAttribute("autoplay");q=parseInt(a.getAttribute("transition-duration"),10);isNaN(q)&&(q=600);a.g={autoplay:n,Z:e,frameWidth:c,frameHeight:u,aa:f,ba:h,U:b,ca:v,transitionDuration:q,ja:d,ia:k}}g.ga=function(){null!=this.h&&(this.stopRotation(),this.F=this.h,X(this,0))};g.ha=function(a){if(this.i){this.H&&(this.H(),this.H=null);a=-a.dx/this.g.frameWidth;var b=Math.round(a);pa(this,this.F+b,a-b)}};
g.fa=function(){if(null!=this.h){X(this,this.g.transitionDuration);var a=this.h;Y(this,a);this.F!=a&&(0==a?E("reachleftend",this):a==this.i-1&&E("reachrightend",this))}};
g.ea=function(a){if(this.i){var b=null;var c=this.m;var d=this.l,e=a.clientX,h=a.clientY,f=c.style["pointer-events"];c.style["pointer-events"]="none";e=d.ownerDocument.elementFromPoint(e,h);c.style["pointer-events"]=f;if(c=e&&F(d,e)?e:null){d=a.clientX;a=a.clientY;f=!1;"gwd-taparea"===c.tagName.toLowerCase()&&(f=c.ownerDocument.createEvent("Event"),f.initEvent("action",!0,!0),f.clientX=d,f.clientY=a,f=!c.dispatchEvent(f));if(f)return;for(a=0;a<this.i;a++)if(F(this.frames[a],c)){b=a;break}null!=b&&
(a=this.g.Z[b])&&!E("frameexit",this,{url:a}).detail.handled&&(a instanceof I||a instanceof I||(a="object"==typeof a&&a.l?a.j():String(a),ka.test(a)||(a="about:invalid#zClosurez"),a=new I(a,J)),da.open(a instanceof I&&a.constructor===I?a.g:"type_error:SafeUrl",""))}null==b&&(b=null!=this.h?this.h:0);E("frametap",this,{element:this.frames[b],id:b+1})}};function X(a,b){a.I=0<b;a.l&&C(a.l,b);for(var c=0;c<a.i;c++)C(a.frames[c],b)}
function Y(a,b){a.frames[b]&&(a.h=b,pa(a,b,0,a.i),a.D.push("frameshown"),a.G[b]||(a.G[b]=!0,--a.J||a.D.push("allframesviewed")));a.I||a.o()}
function pa(a,b,c,d){d=void 0===d?1:d;for(var e=a.g,h,f,k=-d;k<=d;k++)if((h=a.frames[k+b])&&0<=c*k){0>k?f=1-Math.abs(c):0<k?f=Math.abs(c)-1:(S(a,b),a.h=b,f=c);var n=Math.abs(f);h.style.setProperty("transform",y(e.ba*f,e.U*n,e.ca*n,e.aa*f))}a.K!=a.h&&null!=a.h&&(a.K=a.h,E("frameactivated",a,{id:a.currentIndex}));a.l.style.setProperty("transform",y(a.v-(b+c+.5)*e.frameWidth,-e.U,0))}
function V(a){var b=a.hasAttribute("has-navigation"),c=!!a.j;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.j=document.createElement("gwd-gallerynavigation"),a.j.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.j)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.j),a.j=null);a.j&&(H(a,"navigation-highlight",a.j,"highlight"),H(a,"navigation-thumbnails",a.j,"use-thumbnails"));oa(a)}
l.Object.defineProperties(T,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return na}}});customElements.define("gwd-carouselgallery",T);}).call(this);
